language: minimal

services:
    - docker

env:
    global:
        - PARALLELMFLAGS="-j4"
          OPENSSL_UPSTREAM=old/1.1.1/openssl-1.1.1d.tar.gz
          OPENSSL_SHA1=056057782325134b76d1931c48f2c7e6595d7ef4
          INSTALL_SPHINX="yes"

    matrix:
        - OPENSSL_FLAGS=no-ec

        - OPENSSL_FLAGS=
          INSTALL_SPHINX=

        - INSTALL_SPHINX="yes"

        - OPENSSL_UPSTREAM=openssl-3.0.0-alpha16.tar.gz
          OPENSSL_SHA1=9719fde1203a21f768c5688dd7bd579c6b5a8ae4

script:
    - docker build --rm
        --build-arg USER_ID=`id -u`
        --build-arg PARALLELMFLAGS=$PARALLELMFLAGS
        --build-arg OPENSSL_UPSTREAM=$OPENSSL_UPSTREAM
        --build-arg OPENSSL_SHA1=$OPENSSL_SHA1
        --build-arg OPENSSL_BUILD_PARALLEL=$OPENSSL_BUILD_PARALLEL
        --build-arg OPENSSL_FLAGS=$OPENSSL_FLAGS
        --build-arg INSTALL_SPHINX=$INSTALL_SPHINX
        --tag xca .
