language: minimal

services:
    - docker

env:
    global:
        - PARALLELMFLAGS="-j4"
    matrix:
        - INSTALL_SPHINX=""
          OPENSSL_FLAGS=""

        - INSTALL_SPHINX="yes"
        - OPENSSL_FLAGS=no-ec

script:
    - docker build --rm
        --build-arg USER_ID=`id -u`
        --build-arg PARALLELMFLAGS=$PARALLELMFLAGS
        --build-arg OPENSSL_UPSTREAM=$OPENSSL_UPSTREAM
        --build-arg OPENSSL_SHA1=$OPENSSL_SHA1
        --build-arg OPENSSL_BUILD_PARALLEL=$OPENSSL_BUILD_PARALLEL
        --build-arg OPENSSL_FLAGS=$OPENSSL_FLAGS
        --build-arg INSTALL_SPHINX=$INSTALL_SPHINX
        --tag xca .
